[SPR-842]: Run large_data once, but the others multiple times

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -38,7 +38,8 @@ jobs:
       TEST_LOGS_S3_PREFIX: nightly-testlogs
       NUM_PROCS: ${{ vars.NUM_PROCS }}
       #INTEGRATION_TEST_ITERATIONS: ${{ vars.INTEGRATION_TEST_ITERATIONS || 1 }}
-      INTEGRATION_TEST_ITERATIONS: 3
+      INTEGRATION_TEST_ITERATIONS: 2
+      INTEGRATION_FULL_TEST_ITERATIONS: 1
       # The path to the Springtail logs, keep consistent with the `log_path` inside
       # system.json.test
       SPRINGTAIL_LOG_PATH: /opt/springtail/logs
@@ -208,7 +209,7 @@ jobs:
           
             _LOG_FLAG="failed"
             echo "*** Starting iteration $i/${INTEGRATION_TEST_ITERATIONS} of integration tests"
-            python3 test_runner.py -a -c config.yaml -j ${GITHUB_WORKSPACE}/integration-test-report.xml 2>&1 | tee tmplog
+            python3 test_runner.py -c config.yaml -j ${GITHUB_WORKSPACE}/integration-test-report.xml 2>&1 | tee tmplog
             # Grab the success/failure status of the integration tests
             if [ $? -eq 0 ] && ! grep -qE "Tests failed: [1-9][0-9]*" tmplog
             then
@@ -237,6 +238,46 @@ jobs:
             # If the current iteration of test failed, break out of the loop for now
             if [ "$_LOG_FLAG" = "failed" ]; then
               echo "*** Integration test failed at iteration ${i}, breaking out of the loop"
+              exit 1
+            fi
+          done
+
+          for i in $(seq 1 ${INTEGRATION_FULL_TEST_ITERATIONS}) ;
+          do
+            # Note: there might be discrepancies between the _LOG_TIMESTAMP and the _LOG_DATE due to the time it takes to run the integration tests
+            # it may run across a day. This is fine as long as the logs are grouped by _LOG_DATE
+
+            _LOG_FLAG="failed"
+            echo "*** Starting iteration $i/${INTEGRATION_TEST_ITERATIONS} of full integration tests"
+            python3 test_runner.py -a -c config.yaml -j ${GITHUB_WORKSPACE}/integration-test-report.xml 2>&1 | tee tmplog
+            # Grab the success/failure status of the integration tests
+            if [ $? -eq 0 ] && ! grep -qE "Tests failed: [1-9][0-9]*" tmplog
+            then
+              _LOG_FLAG="succeeded"
+            fi
+            echo "*** Finished iteration $i/${INTEGRATION_TEST_ITERATIONS} of full integration tests"
+
+            _TIMESTAMP=$(date +%s)
+
+            # Test logs
+            log_file="integration-full-test-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}-${i}.log"
+            log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
+            aws s3 cp tmplog $log_s3_key
+            echo "*** Integration Full Test Log S3 Key: $log_s3_key"
+            rm -f tmplog
+
+            # Springtail service logs
+            springtail_log_file="springtail-full-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}-${i}.tar.gz"
+            output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../debug)
+            fname=$(echo $output  | cut -f2 -d':' | xargs | head -1)
+            springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_log_file}"
+            aws s3 cp $fname $springtail_log_s3_key
+            echo "*** Springtail Full test Log S3 Key: $springtail_log_s3_key"
+            rm -f $fname
+
+            # If the current iteration of test failed, break out of the loop for now
+            if [ "$_LOG_FLAG" = "failed" ]; then
+              echo "*** Integration full test failed at iteration ${i}, breaking out of the loop"
               exit 1
             fi
           done
