Stop proxy tests from running

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -291,84 +291,84 @@ jobs:
           cd debug
           make install -j ${NUM_PROCS}
 
-      - name: Run Proxy Tests
-        if: success()
-        env:
-          LD_LIBRARY_PATH: /usr/lib/springtail
-        run: |
-          # Make sure Proxy `enable_ssl` is on 
-          sed -i 's/enable_ssl": false/enable_ssl": true/g' system.json.test
-          
-          cd python/testing
-          python3 springtail.py -f ../../system.json.test --kill --build-dir ../../debug
-          
-          if [ $? -ne 0 ]; then
-            exit 1
-          fi
-          
-          cd proxy
-          # Do not break out if errors occur
-          set +e
-          _LOG_FLAG="failed"
-          python3 test_runner_new.py -t -s postgres_all -b ../../../debug
-          if [ $? -eq 0 ]; then
-              _LOG_FLAG="succeeded"
-          fi
-          set -e
-          
-          _TIMESTAMP=$(date +%s)
-          
-          # Test log
-          log_file="proxy-regress-${GITHUB_SHORT_SHA}-${_TIMESTAMP}-${_LOG_FLAG}.log" 
-          log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
-          aws s3 cp proxy_regress.log $log_s3_key
-          echo "*** Proxy Test Log S3 Key: $log_s3_key"
-          
-          # Springtail service logs (proxy)
-          springtail_proxy_log_file="proxy-springtail-svc-${GITHUB_SHORT_SHA}-${_TIMESTAMP}.tar.gz"
-          # tar all logs under the Springtail log path
-          # only do the taring and uploading if there are something inside the log path
-          # checks if the log path is empty
-          if [ "$(ls -A ${SPRINGTAIL_LOG_PATH})" ]; then
-            tar -czf $springtail_proxy_log_file ${SPRINGTAIL_LOG_PATH}/*
-            springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_proxy_log_file}"
-            aws s3 cp $springtail_proxy_log_file $springtail_log_s3_key
-            echo "*** Springtail Proxy Logs S3 Key: $springtail_log_s3_key"
-          else
-            echo "*** No Springtail Proxy Logs to found inside ${SPRINGTAIL_LOG_PATH}"
-          fi
+      # - name: Run Proxy Tests
+      #   if: success()
+      #   env:
+      #     LD_LIBRARY_PATH: /usr/lib/springtail
+      #   run: |
+      #     # Make sure Proxy `enable_ssl` is on
+      #     sed -i 's/enable_ssl": false/enable_ssl": true/g' system.json.test
 
-          # Find the file matching this name exactly: `regression.diff.pg.out`
-          # under the $TMPDIR directory (recursive) and upload it to S3
-          regression_pg_diff_file=$(find /tmp -name "regression.diff.pg.out")
-          # Only upload to S3 if the file exists
-          if [ -f "$regression_pg_diff_file" ]; then
-              regression_pg_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_pg.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
-              aws s3 cp $regression_pg_diff_file $regression_pg_diff_s3_key
-              echo "*** PG Regression Diff S3 Key: $regression_pg_diff_s3_key"
-          fi
-          # Find the file matching this name exactly: `regression.diff.proxy.out`
-          # under the $TMPDIR directory (recursive) and upload it to S3
-          regression_proxy_diff_file=$(find /tmp -name "regression.diff.proxy.out")
-          # Only upload to S3 if the file exists
-          if [ -f "$regression_proxy_diff_file" ]; then
-              regression_proxy_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_proxy.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
-              aws s3 cp $regression_proxy_diff_file $regression_proxy_diff_s3_key
-              echo "*** Proxy Regression Diff S3 Key: $regression_proxy_diff_s3_key"
-          fi
-          # Eventually fail the step
-          if [ "$_LOG_FLAG" = "failed" ]; then
-            # Find the file matching this name exactly: `regression.result.proxy.out`
-            # under the $TMPDIR directory (recursive) and upload it to S3
-            regression_result_diff_file=$(find /tmp -name "regression_result.diff.out")
-            # Only upload to S3 if the file exists
-            if [ -f "$regression_result_diff_file" ]; then
-                regression_result_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_result.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
-                aws s3 cp $regression_result_diff_file $regression_result_diff_s3_key
-                echo "*** Proxy Regression Result Diff S3 Key: $regression_result_diff_s3_key"
-            fi
-            exit 1
-          fi
+      #     cd python/testing
+      #     python3 springtail.py -f ../../system.json.test --kill --build-dir ../../debug
+
+      #     if [ $? -ne 0 ]; then
+      #       exit 1
+      #     fi
+
+      #     cd proxy
+      #     # Do not break out if errors occur
+      #     set +e
+      #     _LOG_FLAG="failed"
+      #     python3 test_runner_new.py -t -s postgres_all -b ../../../debug
+      #     if [ $? -eq 0 ]; then
+      #         _LOG_FLAG="succeeded"
+      #     fi
+      #     set -e
+
+      #     _TIMESTAMP=$(date +%s)
+
+      #     # Test log
+      #     log_file="proxy-regress-${GITHUB_SHORT_SHA}-${_TIMESTAMP}-${_LOG_FLAG}.log"
+      #     log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
+      #     aws s3 cp proxy_regress.log $log_s3_key
+      #     echo "*** Proxy Test Log S3 Key: $log_s3_key"
+
+      #     # Springtail service logs (proxy)
+      #     springtail_proxy_log_file="proxy-springtail-svc-${GITHUB_SHORT_SHA}-${_TIMESTAMP}.tar.gz"
+      #     # tar all logs under the Springtail log path
+      #     # only do the taring and uploading if there are something inside the log path
+      #     # checks if the log path is empty
+      #     if [ "$(ls -A ${SPRINGTAIL_LOG_PATH})" ]; then
+      #       tar -czf $springtail_proxy_log_file ${SPRINGTAIL_LOG_PATH}/*
+      #       springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_proxy_log_file}"
+      #       aws s3 cp $springtail_proxy_log_file $springtail_log_s3_key
+      #       echo "*** Springtail Proxy Logs S3 Key: $springtail_log_s3_key"
+      #     else
+      #       echo "*** No Springtail Proxy Logs to found inside ${SPRINGTAIL_LOG_PATH}"
+      #     fi
+
+      #     # Find the file matching this name exactly: `regression.diff.pg.out`
+      #     # under the $TMPDIR directory (recursive) and upload it to S3
+      #     regression_pg_diff_file=$(find /tmp -name "regression.diff.pg.out")
+      #     # Only upload to S3 if the file exists
+      #     if [ -f "$regression_pg_diff_file" ]; then
+      #         regression_pg_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_pg.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
+      #         aws s3 cp $regression_pg_diff_file $regression_pg_diff_s3_key
+      #         echo "*** PG Regression Diff S3 Key: $regression_pg_diff_s3_key"
+      #     fi
+      #     # Find the file matching this name exactly: `regression.diff.proxy.out`
+      #     # under the $TMPDIR directory (recursive) and upload it to S3
+      #     regression_proxy_diff_file=$(find /tmp -name "regression.diff.proxy.out")
+      #     # Only upload to S3 if the file exists
+      #     if [ -f "$regression_proxy_diff_file" ]; then
+      #         regression_proxy_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_proxy.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
+      #         aws s3 cp $regression_proxy_diff_file $regression_proxy_diff_s3_key
+      #         echo "*** Proxy Regression Diff S3 Key: $regression_proxy_diff_s3_key"
+      #     fi
+      #     # Eventually fail the step
+      #     if [ "$_LOG_FLAG" = "failed" ]; then
+      #       # Find the file matching this name exactly: `regression.result.proxy.out`
+      #       # under the $TMPDIR directory (recursive) and upload it to S3
+      #       regression_result_diff_file=$(find /tmp -name "regression_result.diff.out")
+      #       # Only upload to S3 if the file exists
+      #       if [ -f "$regression_result_diff_file" ]; then
+      #           regression_result_diff_s3_key="${TEST_LOG_S3_FULL_PREFIX}/regression_result.diff.${GITHUB_SHORT_SHA}-${_TIMESTAMP}.out"
+      #           aws s3 cp $regression_result_diff_file $regression_result_diff_s3_key
+      #           echo "*** Proxy Regression Result Diff S3 Key: $regression_result_diff_s3_key"
+      #       fi
+      #       exit 1
+      #     fi
 
       - name: Package and Upload Build artifacts to S3
         if: success()
