Move the performance runner to the right place

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -105,53 +105,6 @@ jobs:
           # This is the prefix for the logs on S3, including the S3 scheme, buket name all the way to the "folder"
           echo "TEST_LOG_S3_FULL_PREFIX=s3://${DEVSUPPORT_BUCKET_NAME}/${TEST_LOGS_S3_PREFIX}/${CURRENT_DATE}" >> $GITHUB_ENV
 
-      - name: Run nightly performance test
-        if: success()
-        run: |
-          cd python/testing
-          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
-
-          cd ../performance
-
-          # Install dependencies
-          pip3 install --break-system-packages -r requirements.txt
-
-          _LOG_FLAG="failed"
-          # Run performance tests
-          python3 performance_runner.py -c performance_config.yaml 2>&1 | tee tmplog
-
-          # Grab the success/failure status of the performance tests
-          if [ $? -eq 0 ] 
-          then 
-            _LOG_FLAG="succeeded"
-          fi
-
-          # Upload performance test logs
-          _TIMESTAMP=$(date +%s)
-          log_file="performance-test-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log" 
-          log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
-          aws s3 cp tmplog $log_s3_key
-          echo "*** Performance Test Log S3 Key: $log_s3_key"
-          rm -f tmplog
-
-          # Go back to the testing folder to use the springtail.py to dump the logs
-          cd ../testing
-
-          # Springtail service logs
-          springtail_log_file="springtail-performance-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.tar.gz"
-          output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../debug)
-          log_dump_file_name=$(echo $output | cut -f2 -d':' | xargs | head -1)
-          springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_log_file}"
-          aws s3 cp $log_dump_file_name $springtail_log_s3_key
-          echo "*** Springtail Log S3 Key: $springtail_log_s3_key"
-          rm -f $log_dump_file_name
-
-          if [ "$_LOG_FLAG" = "failed" ]; then
-            echo "*** Performance test failed"
-            exit 1
-          fi
-          echo "*** Finished running performance tests"
-
       - name: Prepare DB for Unit Tests
         run: |
           service postgresql start
@@ -286,6 +239,53 @@ jobs:
               exit 1
             fi
           done
+
+      - name: Run nightly performance test
+        if: success()
+        run: |
+          cd python/testing
+          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
+
+          cd ../performance
+
+          # Install dependencies
+          pip3 install --break-system-packages -r requirements.txt
+
+          _LOG_FLAG="failed"
+          # Run performance tests
+          python3 performance_runner.py -c performance_config.yaml 2>&1 | tee tmplog
+
+          # Grab the success/failure status of the performance tests
+          if [ $? -eq 0 ] 
+          then 
+            _LOG_FLAG="succeeded"
+          fi
+
+          # Upload performance test logs
+          _TIMESTAMP=$(date +%s)
+          log_file="performance-test-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log" 
+          log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
+          aws s3 cp tmplog $log_s3_key
+          echo "*** Performance Test Log S3 Key: $log_s3_key"
+          rm -f tmplog
+
+          # Go back to the testing folder to use the springtail.py to dump the logs
+          cd ../testing
+
+          # Springtail service logs
+          springtail_log_file="springtail-performance-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.tar.gz"
+          output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../debug)
+          log_dump_file_name=$(echo $output | cut -f2 -d':' | xargs | head -1)
+          springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_log_file}"
+          aws s3 cp $log_dump_file_name $springtail_log_s3_key
+          echo "*** Springtail Log S3 Key: $springtail_log_s3_key"
+          rm -f $log_dump_file_name
+
+          if [ "$_LOG_FLAG" = "failed" ]; then
+            echo "*** Performance test failed"
+            exit 1
+          fi
+          echo "*** Finished running performance tests"
 
       - name: Run nightly build (if above tests pass)
         if: success()
