Fixing nightly to run properly

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -108,24 +108,36 @@ jobs:
       - name: Run nightly performance test
         if: success()
         run: |
-          pwd
-          ls -l
-          cd python/performance
+          cd python/testing
+          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
+
+          cd ../performance
 
           # Install dependencies
           pip3 install --break-system-packages -r requirements.txt
 
+          _LOG_FLAG="failed"
           # Run performance tests
-          python3 performance_runner.py 2>&1 | tee tmplog
+          python3 performance_runner.py -c performance_config.yaml 2>&1 | tee tmplog
+
+          # Grab the success/failure status of the performance tests
+          if [ $? -eq 0 ] 
+          then 
+            _LOG_FLAG="succeeded"
+          fi
 
           # Upload performance test logs
           _TIMESTAMP=$(date +%s)
-          log_file="performance-test-${GITHUB_SHORT_SHA}-${_TIMESTAMP}.log" 
+          log_file="performance-test-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log" 
           log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
           aws s3 cp tmplog $log_s3_key
           echo "*** Performance Test Log S3 Key: $log_s3_key"
           rm -f tmplog
 
+          if [ "$_LOG_FLAG" = "failed" ]; then
+            echo "*** Performance test failed"
+            exit 1
+          fi
           echo "*** Finished running performance tests"
 
       - name: Prepare DB for Unit Tests
