Implemted feat: SPR-317
- Added CI/CD for to run tests (Unit Test, Integration Test) etc.
- Fixed the base Dockerfile to use `tini` as init process (PID 1) in
  order to avoid zombie process issues when killing postgres server
- Upload both unit test and integration tests results up to S3 and to
  the GitHub actions as Artifacts for easy reviews
- Added zombie process status check in Python `running_pids` function,
  just in case.
- Added a cron (every 6 hours) GitHub Action to refresh ECR password,
  since we are using the Docker image from ECR to launch CI/CD
  container.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,67 +9,105 @@ on:
         type: string
         required: true
     secrets:
-      ecr_pw:
-        description: 'The password for the ECR.'
+      aws_ecr_docker_password:
+        description: "The password for the ECR docker registry."
         required: true
 
 jobs:
   test:
     name: test
-    runs-on: ubuntu-latest
-    # Redis
-    services:
-      # Label used to access the service container
-      redis:
-        # Docker Hub image
-        image: redis
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+    runs-on: warp-ubuntu-latest-arm64-4x-spot
+    container:
+      image: ${{ inputs.builder_image_version_tag }}
+      credentials:
+        username: AWS
+        password: ${{ secrets.aws_ecr_docker_password }}
 
+    env:
+      VCPKG_FORCE_SYSTEM_BINARIES: 1
+      DOCKER: 1
+      ZIC: true
+      USER: root
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v4
+      - name: install-aws-cli-action
+        uses: unfor19/install-aws-cli-action@v1
         with:
-          role-to-assume: arn:aws:iam::891377357651:role/GitHubOIDCStack-GHDeploymentRolespringtail4901D08A-77JHxuAaXoIY
-          role-session-name: tempSession
-          aws-region: us-east-1
+          version: 2                         # default
+          verbose: false                     # default
+          arch: arm64
 
-      - name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v2
-
-      - name: Generate temporary Dockerfile
+      - name: Prepare Tests
         run: |
-          echo "FROM ${{ vars.ECR_REPO_URI }}:${{ inputs.builder_image_version_tag }}" > Dockerfile.test
-          echo "WORKDIR /springtail" >> Dockerfile.test
-          echo "COPY ./ /springtail" >> Dockerfile.test
-          echo "COPY ./.docker/system.json.override /springtail/system.json" >> Dockerfile.test
-          echo "RUN rm -rf release debug" >> Dockerfile.test
-          echo "RUN cmake -B debug -S . -D'CMAKE_BUILD_TYPE=Debug'" >> Dockerfile.test
-          echo "RUN make -C debug -j $(nproc)" >> Dockerfile.test
+          git config --global --add safe.directory /__w/springtail/springtail
+          cp system.json.settings system.json.test
+          mkdir -p /opt/springtail/pids
+          service redis-server start
 
-      - name: Setup Buildx
-        uses: docker/setup-buildx-action@v3
+      - name: Build
+        run: |
+          ./clean.sh
+          ./debug.sh -j 4
 
-      - name: Build test image
-        uses: docker/build-push-action@v5
+      - name: Run Unit Tests
+        run: |
+          cd python/testing
+          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
+          cd ../../debug
+          log_file="unit-test-$(date +%s).log" 
+          make test ARGS="--output-junit unit-test-report.xml --output-on-failure --verbose" 2>&1 | tee $log_file
+          unit_test_log_s3key="s3://devsupport.springtail.internal/testlogs/$(date +"%Y/%m/%d/%H")/$log_file"
+          aws s3 cp "$log_file" "$unit_test_log_s3key"
+          echo "*** Unit Test Log S3 Key: $unit_test_log_s3key"
+
+      - name: Unit Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()      # run this step even if previous step failed
         with:
-          context: .
-          file: "Dockerfile.test"
-          tags: localtest:latest
-          load: true
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          push: false
+          name: Unit Tests             # Name of the check run which will be created
+          path: ./debug/unit-test-report.xml
+          reporter: java-junit
+          badge-title: 'unit tests'
 
-      - name: Run Test
-        uses: addnab/docker-run-action@v3
+      - uses: actions/upload-artifact@v4
         with:
-          image: localtest:latest
-          run: |
-            make test -C debug
+          name: 'Unit Test Logs'
+          path: debug/unit-test-*.log
+
+      - name: Create Superuser for test
+        run: |
+          service postgresql start
+          USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='springtail'")
+          if [ "$USER_EXISTS" != "1" ]; then
+            sudo -u postgres psql -c "CREATE USER springtail WITH PASSWORD 'springtail' SUPERUSER LOGIN" 
+          fi
+          service postgresql stop
+
+      - name: Run Integration Tests
+        if: success() || failure()      # run this step even if previous step failed
+        run: |
+          cd python/testing
+          service postgresql start
+          ./startup.sh -s data_init.sql
+          
+          log_file="integration-test-$(date +%s).log" 
+          python3 test_runner.py -c config.yaml -j /__w/springtail/springtail/integration-test-report.xml 2>&1 | tee $log_file
+          integration_test_log_s3key="s3://devsupport.springtail.internal/testlogs/$(date +"%Y/%m/%d/%H")/$log_file"
+          aws s3 cp "$log_file" "$integration_test_log_s3key"
+          echo "*** Integration Test Log S3 Key: $integration_test_log_s3key"
+
+      - name: Integration Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()                         # run this step even if previous step failed
+        with:
+          name: Integration Tests (test_runner)            # Name of the check run which will be created
+          path: ./integration-test-report.xml
+          reporter: java-junit
+          badge-title: 'integration tests'
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: 'Integration Test Logs'
+          path: ./python/testing/integration-test-*.log
